module.exports = {
  OSC_PATHS: {
    alive: '/vbs/alive',
    deskLock: '/vbs/desklock',
    showMode: '/vbs/showmode',
    syncRepository: '/vbs/sync/repository',
    syncProject: '/vbs/sync/project',
    flag: '/vbs/flag',
    flags: '/vbs/flags',
    color: '/vbs/color',

    midiSender: '/vbs/midi/sender',
    midiSenderStart: '/vbs/midi/sender/start',
    midiSenderStop: '/vbs/midi/sender/stop',
    midiReceiver: '/vbs/midi/receiver',
    midiReceiverRefresh: '/vbs/midi/receiver/refresh',

    timecodePlay: '/vbs/timecode/play',
    timecodePause: '/vbs/timecode/pause',
    timecodeStop: '/vbs/timecode/stop',
    timecodeReset: '/vbs/timecode/reset',
    timecodeSender: '/vbs/timecode/sender',
    timecodeReceiver: '/vbs/timecode/receiver',
    timecodeLtcLevel: '/vbs/timecode/ltc_level',
    timecodeLtcLevelReset: '/vbs/timecode/ltc_level/reset',
    timecodeExternalDelay: '/vbs/timecode/external_delay',
    timecodeExternalDelayReset: '/vbs/timecode/external_delay/reset',
    timecodeGeneratorDelay: '/vbs/timecode/generator_delay',
    timecodeGeneratorDelayReset: '/vbs/timecode/generator_delay/reset',
    timecodeRefresh: '/vbs/timecode/refresh',
    timecodeRestartRx: '/vbs/timecode/restart_rx',
    timecodePresetLoad: '/vbs/timecode/preset/load',
    timecodePresetPlay: '/vbs/timecode/preset/play',
    timecodePresetMasterPreroll: '/vbs/timecode/preset/master_preroll',
  },

  BOOLEAN_TARGETS: {
    timecode_sender: 'timecode_sender',
    timecode_receiver: 'timecode_receiver',
    midi_sender: 'midi_sender',
    midi_receiver: 'midi_receiver',
    desk_lock: 'desk_lock',
    show_mode: 'show_mode',
  },
}
